blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions
    url: https://github.com/andrelandgraf/flash-me/discussions
    about: Please ask and answer questions here.
  - name: 💬 Remix Discord Channel
    url: https://rmx.as/discord
    about: Interact with other people using Remix 📀
  - name: 💬 New Updates (Twitter)
    url: https://twitter.com/andrelandgraf94
    about: Follow me for more cool web dev content!
